### ISSUE TITLE
About Generator

### ISSUE THREAD

**Issue by chester256** [zysxmu/IntraQ#2]
Hi, thanks for your work! 
It seems that there is a generator being trained in trainer_direct.py, while the paper says the data for fine-tuning is obtained by optimizing Gaussian noise but not a generator. I am not familiar with zero-shot quantization, and this makes me confused. Could you please help me figure it out? Thanks!

**Comment by chester256** [comment]
Moreover, the images generated by stage 1 still seem to be Gaussian noises. Is that normal?
![image](https://user-images.githubusercontent.com/18751402/160867990-77fb2fda-e5e4-4f9a-85e5-458c1f34f71a.png)

**Comment by zysxmu** [comment]
For question1 (''It seems that there is a generator being trained in trainer_direct.py, while the paper says the data for fine-tuning is obtained by optimizing Gaussian noise but not a generator.'') : 

The generator is only used to produce Gaussian noise-like data in the first several epochs for calibrating the clipping value for activations. Such a special mechanism comes from GDFQ. For a fair comparison with GDFQ, we adopt this mechanism in ZeroQ, ZeroQ+IL, DSG, DSG+IL, ours (IntraQ).

For question2 (Moreover, the images generated by stage 1 still seem to be Gaussian noises. Is that normal?):

Yes, despite I haven't drawn this generated image but I think this is normal as the key in Zero-shot quantization is to produce fake data that match the distribution (learned by the neural network) instead of producing the (human) visual realistic image.
